### PR TITLE
Or make it more English Friendly

### PR DESCRIPTION
**Pull request by orcutt989**
More English-friendly version.

for #37 and #29

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Now, I merged the other pull-request. Would you like to resolve the conflict?

**Comment by niccokunzmann** [comment]
Do you also see this button? 
grafik

**Comment by orcutt989** [comment]
Thanks - I gave you 2 options though for your tutorial. This option is more complicated and changes it. I left it up to you which one you wanted to merge. The previous one leaves it with German words which is fine, it just needs additional instruction.  This one is more generalized for English competency. Which one do you prefer?

**Comment by niccokunzmann** [comment]
I prefer this one.
I will merge it.

**Pull request merged**
