### PR TITLE
Update 00-01-introduction.html grammatically

### PR DESCRIPTION
**Pull request by DaricusDuncan**
Changed 'reglar' to 'regular'
Placed a comma after 'expressions'
Placed the comma after 'and' and placed after 'correct'

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by DaricusDuncan** [comment]
@niccokunzmann Thank you so much for allowing me to help. I will continue to help support this because I really love the whole idea of this and I feel that I can learn and improve myself while helping you. I really did not know if I was doing the work correctly. I created a pull request after the fork I did and just crossed my fingers that everything was done the right way.

**Comment by niccokunzmann** [comment]
@DaricusCodePath So you know, what I value at this pull-request:
- It has a short description which sums up the change `Update 00-01-introduction.html grammatically`
- You used the long description to describe the change in more detail
- The checks run through, so I can be sure the content goes live immediately and not extra by me work is required.
grafik
- The pull-request and commit is a small, coherent change - all changes are summed up under "grammar" and I do not see where one correction could be useful without the other. Context: A commit can be reverted if it is not needed in the future. If a commit contains two changes of which one should be reverted but the other one should not be reverted, it can not be done by git or a click of a button but must be done by hand. To keep the [git history](https://github.com/CoderDojoPotsdam/regex-tutorial/commits/master) understandable and managable, there should be those small, descriptive, coherent commits. Exampe: A commit named "Add feature X and Feature Y" can often be split into two commits.
- With all these points satisfied, the form of this pull-request is more understandable to me than many of my commits.

**Comment by DaricusDuncan** [comment]
@niccokunzmann  

Thank you so much for providing feedback and context on how pull requests work and benefit you. I will continue to provide detail and be thorough. I am really glad that you explained that it is ideally better to make multiple commits that are small are specific than one large commit that has parts that may not be needed.

I really appreciate all of the help. I am adjusting to all of this so you are really awesome for providing the feedback and everything. Thanks again as always.

**Pull request merged**
