### PR TITLE
refactor tutorial

### PR DESCRIPTION
**Pull request by niccokunzmann**
- move js code from tutorial.html to js file #110
- use - in front of jekyll commands to remove white space #111
- remove test output of language tag #110
- remove jquery because the selected language is selected in jekyll #110

### CODE REVIEW

**Comment by DaricusDuncan** [comment]
@niccokunzmann  Everything looks great. Is there anything specific you needed me to do for this?

**Comment by niccokunzmann** [comment]
@DaricusDuncan No, nothing specific. Thanks for having a look. Through pull requests we can spread knowledge and appreciation :) If you like, you can merge.

**Comment by niccokunzmann** [comment]
I merged it to not forget it. Thanks for reviewing :)

**Comment by DaricusDuncan** [comment]
@niccokunzmann You are welcome. I forgot to respond back to you yesterday, but I did not have access to merge. The button to merge was not clickable. I should have told you sooner.

**Pull request merged**
