### PR TITLE
Update

### PR DESCRIPTION
**Pull request by DaricusDuncan**

### CODE REVIEW

**Comment by DaricusDuncan** [comment]
Sorry, I was trying to update my cloned repo. Just ignore!

**Comment by niccokunzmann** [comment]
All fine. If you need help, ask.

**Comment by DaricusDuncan** [comment]
Thank you so much! Please help me if you can. I was trying to use the video on GitHub to update my local copy and the interface is slightly different so if you happen to know the proper steps please provide them for me if it is not too much trouble.

**Comment by niccokunzmann** [comment]
Maybe this tutorial can clarify it, if you have 15 minutes: https://try.github.io/
Which commands of this tutorial would you use to get to the desired state?

**Comment by DaricusDuncan** [comment]
Hi,

Sorry for the long wait but after going through the exercise I believe that I should use a **_git pull origin master_** to update my files on my local repo. Is this correct?

**Comment by niccokunzmann** [comment]
It looks good to me. So, I do not know as I do not know your state of the repo but I recommend trying it out. What is the outcome? I believe it is the right thing to do.

**Comment by DaricusDuncan** [comment]
I tried it and it worked perfectly. Thank you for introducing me to Try.GitHub.io. Still a newbie so I am learning. I appreciate you taking the time to help me.

screen shot 2017-10-07 at 6 39 22 am

**Comment by niccokunzmann** [comment]
I see you are ahead... I will have a look at your changes :)

**Comment by niccokunzmann** [comment]
Ah, I see three things:

- You added your editor configuration, I think it is eclipse... https://github.com/CoderDojoPotsdam/regex-tutorial/commit/47ab6e7579975c96a4bbd18bce78565e9a9c0518
  This is usually not needed as it can generate merge conflicts with other people also using eclipse.
  If you do not want to commit those files, you can add them to the [.gitignore file](https://github.com/CoderDojoPotsdam/regex-tutorial/blob/master/.gitignore).
- I would say, you are [using a mac](https://github.com/CoderDojoPotsdam/regex-tutorial/commit/47ab6e7579975c96a4bbd18bce78565e9a9c0518#diff-709b322d95fc15d5133c5478adb47c6cR3) :)
- You also merged the translations branch which was a proposal which we do not use any more.

So, if you would like to get your master branch to the same state as the master branch of CoderDojoPotsdam/regex-tutorial, you would need to remove the changes or delete the files and create a pull-request with the .idea entry in the .gitignore file.

1. Delete the commits from the master branch
    1. I think, you can use `git rebase -i HEAD~5` to view the last 5 commits and decide which commits you would like to use
    2. you can remove the commits until there is only the old version of the master branch
    3. you pull again as you did before.
    4. You do `git push -f` - a force push which changes the history of your master branch.
2. Or you can checkout an other branch, delete the master branch and checkout the master branch of origin master.
3. you delete the files, add `.idea` to the `.gitignore` file and I will accept your pull-request.

I do not know what you would like to achieve and if you want to do any of this. You can try it out if you like ^^
PS: There is another tutorial which was recommended to me: https://rogerdudler.github.io/git-guide/index.html

**Comment by DaricusDuncan** [comment]
Actually, I am interested in doing all of this to get the repo where it needs to be. I am learning so much and this is helpful information to know if I want to continue to be able to help out on this project.

1. I am using a Mac :) !
2. This is really fun and exciting for me.
3. I appreciate the help a ton!

Let me go through all of the information you have provided and see what happens. I am going to take a whack at this and if I get stuck I will reach out again.

**Comment by DaricusDuncan** [comment]
Alright, I first want to say thank you for all of the help. 

I ended up creating another branch and pulling your **origin/master** and making that my master
on my local repo.

I then did the **git push -f** and updated GitHub and reset my **origin** to my .git GitHub location.

Thank you so much for the help.  

I actually did not do any code yet to do a pull request actually. The goal of today was to attempt to make a button for the languages but ended up learning more about git today. All in all, I am still learning so it is all good.

screen shot 2017-10-07 at 9 27 30 pm

**Pull request closed without merging**
